#!/bin/sh

set -euo pipefail

# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

echo "----------- source this file ------------------"
echo $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"
echo "-----------------------------------------------"

# Processing
while true
do
  HEADERS="$(mktemp)"

  echo "----------- HEADERS FILE ------------------"
  echo $(mktemp)
  echo "------------------------------------------------"

  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

  echo "----------- variables ------------------"
  # HEADERS: HTTP/1.1 200 OK
  # Content-Type: application/json
  # Lambda-Runtime-Aws-Request-Id: 037111c0-f958-11e8-a09e-277a3f1da356
  # Lambda-Runtime-Deadline-Ms: 1544101707623
  # Lambda-Runtime-Invoked-Function-Arn: arn:aws:lambda:eu-west-3:XXXXXXXXXXXX:function:bash-function
  # Date: Thu, 06 Dec 2018 13:08:24 GMT
  # Content-Length: 16
  echo "LAMBDA_TASK_ROOT: "$LAMBDA_TASK_ROOT # /var/task
  echo "_HANDLER: "$_HANDLER # function.handler
  echo "EVENT_DATA: "$EVENT_DATA # { "text": "Hello" }

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done